[package]
name = "example"
version = "0.0.1"
authors = ["Ivan Ukhov <ivan.ukhov@gmail.com>"]

[dependencies]
arguments = "*"
configuration = "*"
log = "*"
sql = "*"
sqlite = "*"
streamer = { git = "https://github.com/learning-on-chip/streamer.git" }
term = "*"
